[package]
name = "grades"
version = "0.9.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.140"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
